import java_cup.runtime.*;

/*Terminales*/
terminal MAS, MENOS, POR, DIV;
terminal Integer NUMERO;

/*No terminales*/
non terminal linea;
non terminal Integer exp;

/*Precedencias*/

precedence left MAS, MENOS;
precedence left POR, DIV;

/*Gramatica*/
linea ::= exp:result {:System.out.println(result);:} linea
	| exp:result {:System.out.println(result);:}
	;		

exp	::=  MAS exp:e1 exp:e2			{: RESULT = e1+e2; :}
	|  MENOS exp:e1  exp:e2			{: RESULT = e1-e2; :}
	| POR exp:e1  exp:e2 			{: RESULT = e1*e2; :}
	|  DIV exp:e1  exp:e2			{: RESULT = e1/e2; :}
	| NUMERO:n						{: RESULT= n; :}
	;