import java_cup.runtime.*;

/*Terminales*/
terminal MAS, MENOS, POR, DIV;
terminal AP, CP;
terminal String NUMERO, IDENT;

/*No terminales*/
non terminal linea;
non terminal String exp;

/*Precedencias*/

precedence left MAS, MENOS;
precedence left POR, DIV;

precedence left AP, CP;

/*Gramatica*/
linea ::= exp:result {:System.out.println(result);:} linea	
		| exp:result {:System.out.println(result);:}
		;

exp	::=  exp:e1 MAS exp:e2			{: RESULT = e1+" "+e2+" + "; :}
	|  exp:e1 MENOS exp:e2			{: RESULT = e1+" "+e2+" - "; :}
	|  exp:e1 POR exp:e2 			{: RESULT = e1+" "+e2+" * "; :}
	|  exp:e1 DIV exp:e2			{: RESULT = e1+" "+e2+" / "; :}
	| NUMERO:n						{: RESULT= n; :}
	| AP exp:e CP					{: RESULT= e; :}
	| IDENT:i 						{: RESULT = i; :}
	;